"""empty message

Revision ID: 2cf77fbc5103
Revises: 
Create Date: 2020-12-11 21:59:51.437635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf77fbc5103'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('drink_name', sa.String(length=250), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('measurements', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('drink_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'drink_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('favorites')
    op.drop_table('drinks')
    # ### end Alembic commands ###
