"""empty message

Revision ID: 7a6c528f75b7
Revises: 48d2fc81a0f0
Create Date: 2021-01-26 22:54:18.614821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6c528f75b7'
down_revision = '48d2fc81a0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('drink_img', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'drink_img')
    # ### end Alembic commands ###
